package output

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/go-github/v68/github"
	"github.com/vhco/upgrade-guard/internal/analyst"
)

const commentMarker = "<!-- upgrade-guard -->"

// PostGitHubComment posts (or updates) a PR comment with the analysis result.
func PostGitHubComment(ctx context.Context, client *github.Client, owner, repo string, prNumber int, result *analyst.AnalysisResult) error {
	body := formatPRComment(result)

	// Look for an existing comment to update
	existingID, err := findExistingComment(ctx, client, owner, repo, prNumber)
	if err != nil {
		return fmt.Errorf("searching for existing comment: %w", err)
	}

	if existingID != 0 {
		_, _, err = client.Issues.EditComment(ctx, owner, repo, existingID, &github.IssueComment{
			Body: github.Ptr(body),
		})
		if err != nil {
			return fmt.Errorf("updating comment: %w", err)
		}
		return nil
	}

	_, _, err = client.Issues.CreateComment(ctx, owner, repo, prNumber, &github.IssueComment{
		Body: github.Ptr(body),
	})
	if err != nil {
		return fmt.Errorf("creating comment: %w", err)
	}
	return nil
}

func findExistingComment(ctx context.Context, client *github.Client, owner, repo string, prNumber int) (int64, error) {
	opts := &github.IssueListCommentsOptions{
		ListOptions: github.ListOptions{PerPage: 100},
	}

	for {
		comments, resp, err := client.Issues.ListComments(ctx, owner, repo, prNumber, opts)
		if err != nil {
			return 0, err
		}

		for _, c := range comments {
			if strings.Contains(c.GetBody(), commentMarker) {
				return c.GetID(), nil
			}
		}

		if resp.NextPage == 0 {
			break
		}
		opts.Page = resp.NextPage
	}

	return 0, nil
}

func formatPRComment(result *analyst.AnalysisResult) string {
	var b strings.Builder

	b.WriteString(commentMarker + "\n")
	b.WriteString("## 🛡️ Upgrade Guard — Risk Assessment\n\n")

	if result.RawMarkdown != "" {
		b.WriteString(result.RawMarkdown)
	} else {
		for i, a := range result.Assessments {
			if i > 0 {
				b.WriteString("\n---\n\n")
			}
			riskEmoji := "🟢"
			riskLabel := "LOW RISK"
			switch a.Risk {
			case analyst.RiskMedium:
				riskEmoji = "🟡"
				riskLabel = "MEDIUM RISK"
			case analyst.RiskHigh:
				riskEmoji = "🔴"
				riskLabel = "HIGH RISK"
			}

			fmt.Fprintf(&b, "### %s `%s` → `%s`  %s %s\n\n",
				a.Component.Name,
				a.Component.FromVersion, a.Component.ToVersion,
				riskEmoji, riskLabel)

			if a.Markdown != "" {
				b.WriteString(a.Markdown)
			} else {
				b.WriteString(a.Summary)
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("\n---\n")
	fmt.Fprintf(&b, "\n*Generated by [Upgrade Guard](https://github.com/vhco/upgrade-guard) • Guard level: %s*\n", result.GuardLevel)

	return b.String()
}
